#%RAML 1.0 NamedExample2
Example1:
    [
        {
            "adress": "170, Avenue Orchard",
            "arron_id": 5.0,
            "equipement_inst": "",
            "gestion_inst": "Privé",
            "id": 77.0,
            "nom_installation": "Parc Hayward",
            "position": {
                "id": 64.0,
                "latitude": "45.423339",
                "longitude": "-73.648129",
                "point_x": "293208,1671",
                "point_y": "5031500121"
            },
            "propriete_installation": "Municipale",
            "type_installation": "Jeu d'eau"
        }
    ]

Example2:
    [
        {
            "adress": "300, Rue Clément",
            "arron_id": 5.0,
            "equipement_inst": "",
            "gestion_inst": "Privé",
            "id": 123.0,
            "nom_installation": "Parc Ménard",
            "position": {
                "id": 103.0,
                "latitude": "45.433645",
                "longitude": "-73.653179",
                "point_x": "292815,8028",
                "point_y": "5032646392"
            },
            "propriete_installation": "Municipale",
            "type_installation": "Piscine extérieure"
        },
        {
            "adress": "Rue Bergevin",
            "arron_id": 5.0,
            "equipement_inst": "",
            "gestion_inst": "Privé",
            "id": 291.0,
            "nom_installation": "Parc Ménard",
            "position": {
                "id": 103.0,
                "latitude": "45.433645",
                "longitude": "-73.653179",
                "point_x": "292815,8028",
                "point_y": "5032646392"
            },
            "propriete_installation": "Municipale",
            "type_installation": "Jeu d'eau"
        }
    ]