#%RAML 1.0 NamedExample
Example1:
    "arron_id": "Missing data for required field."

Example2:
    "message": "arrondissement does not exist!"

Example3:
    "adress": "Shorter than minimum length 1."
