#%RAML 1.0 NamedExample
myExample1:
    "arron_id": "Missing data for required field."

myExample2:
    "message": "arrondissement does not exist!"

myExample3:
    "adress": "Shorter than minimum length 1."
