#%RAML 1.0 NamedExample2
Example1:
    {
        "arrose": [
            "Missing data for required field."
        ]
    }
Example2:
    {
        "ouvert": [
            "Missing data for required field."
        ]
    }
