#%RAML 1.0 NamedExample2
Example1:
    {
        "arron_id": 5.0,
        "conditions": [
            {
                "arrose": false,
                "date_heure": "2013-12-02T15:57:47",
                "deblaye": false,
                "id": 53514.0,
                "ouvert": false,
                "patinoire_id": 61.0,
                "resurface": false
            },
            {
                "arrose": true,
                "date_heure": "2013-12-12T16:15:57",
                "deblaye": false,
                "id": 53515.0,
                "ouvert": false,
                "patinoire_id": 61.0,
                "resurface": false
            }
        ],
        "id": 61.0,
        "nom_pat": "Anneau à patiner ,  parc Hayward (PPL)"
    }