#%RAML 1.0
title: Data API for homework2 of INF5190 
protocols: [ HTTP ] 
baseUri: https://flask-data-swarm.herokuapp.com/
version: v1
mediaType: application/json
types:
  CreatedFollowedArrondissement:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      profile_id:
        type: number
  PostedProfile:
    type: object
    properties: 
      complete_name:
        type: string
        required: true
      email:
        type: string
        required: true
      followed_arr:
        type: string[]
        required: true
  CreatedProfile:
    type: object
    properties: 
      complete_name:
        type: string
        required: true
      email:
        type: string
        required: true
      followed_arr:
        type: CreatedFollowedArrondissement[]
        required: true
      id:
        type: number
  Arrondissement:
    type: object
    properties:
      id:
        type: integer
        required: false
      name:
        type: string
        required: true
      cle:
        type: string
        required: false
  Glissade:
    type: object
    properties:
      name:
        type: string
        required: true
      date_maj:
        type: string
        required: true
      ouvert:
        type: string
        required: true
      deblaye:
        type: string
        required: true
      condition:
        type: string
        required: true
      arrondissement_id:
        type: number
        required: true
  AQUAINSTFORUPDATE:
    type: object
    properties: 
        arron_id:
          type: number
          required: true
        adress: 
          type: string
          required: true
        equipement_inst:
          type: string
          required: true
        gestion_inst:
          type: string
          required: true
        nom_installation:
          type: string
          required: true
        position_id:
          type: number
          required: true
        propriete_installation:
          type: string
          required: true
        type_installation:
          type: string
          required: true
  UpdatedGlissade:
    type: object
    properties: 
      name:
        type: string
        required: true
      date_maj:
        type: string
        required: true
      ouvert:
        type: boolean
        required: true
      deblaye:
        type: boolean
        required: true
      condition:
        type: string
        required: true
      arrondissement_id:
        type: number
        required: true
  AQUAINST:
    type: object
    properties: 
      id:
        type: number
        required: true
      nom_installation:
        type: string
        required: true
  GLISSADES:
    type: object
    properties: 
      id:
        type: number
        required: true
      name:
        type: string
        required: true
  PATINOIRES:
    type: object
    properties: 
      id:
        type: number
        required: true
      nom_pat:
        type: string
        required: true
  PATINOIRE:
    type: object
    properties:
      id:
        type: number
        required: true
      arron_id:
        type: number
        required: true
      nom_pat:
        type: string
        required: true
      conditions:
        type: CONDITION[]
        required: true
  CONDITION:
    type: object
    properties: 
      id:
        type: number
        required: true
      arrose: 
        type: boolean
        required: true
      date_heure:
        type: datetime
        required: true
      deblaye:
        type: boolean
        required: true
      ouvert:
        type: boolean
        required: true
      resurface:
        type: boolean
        required: true
      patinoire_id:
        type: number
        required: true
  INSTALLATIONS:
    type: object
    properties: 
      id:
        type: number
        required: true
      arr_name:
        type: string
        required: true
      arr_cle:
        type: string
        required: true
      aqua_inst:
        type: AQUAINST[]
        required: true
      glissades:
        type: GLISSADES[]
        required: true
      patinoires:
        type: PATINOIRES[]
        required: true
  Error:
    type: object
    properties: 
       message:
        type: string   

/api:
  /installations:
      get:
          queryParameters: 
              arrondissement:
                description: Arrondissement name
                type: string
                required: true 
          description: Get all installations by arrondissement name.
          responses:
              200:
                body:
                  application/json:
                    type: INSTALLATIONS
                    example: |
                      {
                          "id": 13,
                          "aqua_inst": [
                                {
                                    "id": 2,
                                    "nom_installation": "Saint-Jean-Baptiste"
                                },
                                {
                                    "id": 52,
                                    "nom_installation": "Piscine intérieure Roussin"
                                }
                              ],
                          "arr_cle": null,
                          "arr_name": "Rivière-des-Prairies–Pointe-aux-Trembles",
                          "glissades": [
                                {
                                    "id": 1,
                                    "name": "Aire de glissade ,Don-Bosco"
                                },
                                {
                                    "id": 2,
                                    "name": "Aire de glissade,François-Vaillancourt"
                                }
                              ],
                          "patinoires": [
                                {
                                    "id": 156,
                                    "nom_pat": "Aire de glissade ,Don-Bosco ()"
                                },
                                {
                                    "id": 157,
                                    "nom_pat": "Aire de glissade,François-Vaillancourt ()"
                                }
                              ]
                      }    

      /arrondissement:
          /{arrondissementName}:
            uriParameters:
              arrondissementName:
                type: string
            /glissade:
                /{glissadeName}:  
                    uriParameters:
                        glissadeName:
                            type: string
                    get:
                        description: Get a glissade by name and arrondissement name
                        responses:
                            200:
                                body:
                                    application/json:
                                        type: UpdatedGlissade
                                        example: |
                                            {
                                                "arrondissement_id": 13.0,
                                                "condition": "N/A",
                                                "date_maj": "2014-08-17T14:58:57.600623",
                                                "deblaye": false,
                                                "id": 1.0,
                                                "name": "Aire de glissade ,Don-Bosco",
                                                "ouvert": false
                                            }
                            400:
                                body:
                                  application/json:
                                    type: Error
                                    example:  
                                        {"Message": "arrondissement does not exist" } |
                                        {"Message": "Glissade does not exist!" }
            /aquatique:  
                /{aquatiqueName}:
                    uriParameters:
                        aquaName:
                            type: string
                    get:
                        description: Get a aqua installation by name and arrondissement name
                        responses:
                            200:
                                body:
                                  application/json:
                                    type: Object
                                    examples: !include examples/2aquaInst.raml
                            404:
                                body:
                                  application/json:
                                    type: Error
                                    example:  
                                          {
                                              "message": "Aqua inst does not exist",
                                              "status": "fail"
                                          }
            /patinoire:  
                /{patinoireName}:
                    uriParameters:
                        patinoireName:
                            type: string
                    get:
                        description: Get a patinoire details by name and arrondissement name
                        responses:
                            200:
                                body:
                                  application/json:
                                    type: PATINOIRE
                                    examples: !include examples/patconditions.raml
                            404:
                                body:
                                  application/json:
                                    type: Error
                                    example:  
                                          {
                                              "Message": "Patinoire does not exist"
                                          }

  /profile:
    post:
      description: create a profile
      headers: 
      body: 
        application/json:
          type: PostedProfile
          example: 
            {
	            "complete_name": "mokhtar safir",
	            "email": "safir-mokhtar-2@hotmail.fr",
	            "followed_arr": ["arrondissement1", "arrondissement2", "arrondissement3"]
            }
      responses:
        201:
          body:
            application/json:
              type: CreatedProfile
              example: |
                {
                  "complete_name": "mokhtar safir",
                  "email": "safir-mokhtar-2@hotmail.fr",
                  "followed_arr": [
                      "{'id': 18, 'name': 'arrondissement1', 'profile_id': 6}",
                      "{'id': 19, 'name': 'arrondissement2', 'profile_id': 6}",
                      "{'id': 20, 'name': 'arrondissement3', 'profile_id': 6}",
                      "{'id': 21, 'name': 'arrondissement4', 'profile_id': 6}"
                    ],
                  "id": 6.0
                }
        400:
          body:
            application/json:
              type: Error
              example: 
                {"Message": "The provided email is already in use"}
  /glissade:
    /{id}:
        uriParameters:
          id:
            type: number
            description: Glissade identifier
        put:
          description: edit the state of a glissade
          headers: 
          body: 
            application/json:
              type: Glissade
              example: 
                {
                    "name": "Aire de glissade,Saint-Joseph",
                    "date_maj": "2014-08-17T14:58:57.600623+00:00",
                    "ouvert": "0",
                    "deblaye": "0",
                    "condition": "N/A",
                    "arrondissement_id": 13
                }
          responses:
            200:
                body:
                    application/json:
                    type: UpdatedGlissade
                    example: |
                        {
                            "arrondissement_id": 13.0,
                            "condition": "N/A",
                            "date_maj": "2014-08-17T14:58:57.600623",
                            "deblaye": false,
                            "id": 1.0,
                            "name": "Aire de glissade ,Don-Bosco",
                            "ouvert": false
                        }
            400:
                body:
                  application/json:
                    type: Error
                    example:  
                        {"Message": "arrondissement does not exist" } |
                        {"Message": "Glissade does not exist!" }
        delete:
          description: Remove a glissade
          headers:
              Authorization:
                  type: string
                  description: Basic authentication header
                  example: |
                      Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
          responses:
            200:
                body:
                  application/json:
                      type: UpdatedGlissade
                      example: |
                          {
                              "arrondissement_id": 13.0,
                              "condition": "N/A",
                              "date_maj": "2014-08-17T14:58:57.600623",
                              "deblaye": false,
                              "id": 1.0,
                              "name": "Aire de glissade ,Don-Bosco",
                              "ouvert": false
                          }
            404:
                body:
                  application/json:
                      type: Error
                      example: |
                          { "status":"fail", "message":"glissade does not exist"}
        get:
            description: Get a glissade
            responses:
                200:
                  body:
                    application/json:
                      type: Glissade
                      example: |
                          {
                              "arrondissement_id": 13.0,
                              "condition": "N/A",
                              "date_maj": "2021-10-18T13:45:13",
                              "deblaye": false,
                              "id": 5.0,
                              "name": "Aire de glissade,Saint-Joseph",
                              "ouvert": false
                          }
                404:
                    body:
                      application/json:
                        type: Error
                        example: |
                            {"message": "Glissade does not exist"}
  /installation_aquatique:
    /{id}:
        uriParameters:
          id:
            type: number
            description: Aqua installation identifier
        put:
          description: edit the state of am aqua installation
          headers: 
          body: 
            application/json:
              type: AQUAINSTFORUPDATE
              example: |
                {
                    "adress": "Undefined Undefined",
                    "arron_id": 22,
                    "equipement_inst": "N/A",
                    "gestion_inst": "Undefined Undefined",
                    "nom_installation": "Piscine Jonh F. Kennedy",
                    "position_id": 255,
                    "propriete_installation": "Undefined Undefined Undefined",
                    "type_installation": "Piscine intérieure"  
                }
          responses:
              200:
                  body:
                      application/json:
                          type: AQUAINSTFORUPDATE
                          example: |
                              {
                                  "adress": "Undefined Undefined",
                                  "arron_id": 22.0,
                                  "equipement_inst": "N/A",
                                  "gestion_inst": "Undefined Undefined",
                                  "id": 310.0,
                                  "nom_installation": "Piscine Jonh F. Kennedy",
                                  "position_id": 255.0,
                                  "propriete_installation": "Undefined Undefined Undefined",
                                  "type_installation": "Piscine intérieure"
                              }
              400:
                  body:
                    application/json:
                      type: Error
                      examples: !include examples/aquaInstexample.raml
              404:
                  body:
                    application/json:
                      type: Error
                      example:
                        {"message": "Aqua installation does not exist!"}
                                          
                                    
                          
        delete:
          description: Remove an aqua installation
          headers:
              Authorization:
                  type: string
                  description: Basic authentication header
                  example: |
                      Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
          responses:
            200:
                body:
                  application/json:
                      type: object
                      example: |
                          {
                              "adress": "12 125, Rue Notre-Dame Est",
                              "arron_id": 13.0,
                              "equipement_inst": "Piscine récréative",
                              "gestion_inst": "Municipale",
                              "id": 52.0,
                              "nom_installation": "Piscine intérieure Roussin",
                              "position_id": 46.0,
                              "propriete_installation": "Municipale",
                              "type_installation": "Piscine intérieure"
                          }
            404:
                body:
                  application/json:
                      type: Error
                      example: |
                         {"message": "Aqua inst does not exist","status": "fail"}
            401:
                body:
                  application/json:
                      type: Error
                      example: |
                          {
                              "message": "Please authenticate."
                          }
                                      
        get:
          description: Get details of a specific aqua installation by id
          responses: 
              200:
                  body:
                      application/json:
                          type: object
                          example: |
                              [
                                  {
                                      "adress": "12 125, Rue Notre-Dame Est",
                                      "arron_id": 13.0,
                                      "equipement_inst": "Piscine récréative",
                                      "gestion_inst": "Municipale",
                                      "id": 52.0,
                                      "nom_installation": "Piscine intérieure Roussin",
                                      "position": {
                                          "id": 46.0,
                                          "latitude": "45.640791",
                                          "longitude": "-73.491213",
                                          "point_x": "305485,4766",
                                          "point_y": "5055655173"
                                      },
                                      "propriete_installation": "Municipale",
                                      "type_installation": "Piscine intérieure"
                                  }
                              ]
              404:
                  body:
                    application/json:
                        type: Error
                        example:
                              {
                                  "message": "Aqua inst does not exist",
                                  "status": "fail"
                              }
  /patinoire:
    /{id}:
        uriParameters:
          id:
            type: number
            description: Patinoire identifier
        put:
          description: edit the state of a patinoire
          headers: 
          body: 
            application/json:
              type: Object
              example: 
                  {
                      "nom_pat": "Anneau à patiner ,  parc Hayward (PPL)"
                  }
          responses:
              200:
                  body:
                      application/json:
                          type: Object
                          example: 
                              {
                                  "nom_pat": "Anneau à patiner ,  parc Hayward (PPL)"
                              }
              400:
                  body:
                    application/json:
                      type: Error
                      examples: !include examples/patinoirexample.raml
              404:
                  body:
                    application/json:
                      type: Error
                      example:
                        {"message": "Patinoire does not exist!"}
                                          
                                    
                          
        delete:
          description: Remove a patinoire by id
          headers:
              Authorization:
                  type: string
                  description: Basic authentication header
                  example: |
                      Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
          responses:
            200:
                body:
                  application/json:
                      type: object
                      example: |
                          {
                              "nom_pat": "Aire de glissade ,Don-Bosco ()"
                          }
            404:
                body:
                  application/json:
                      type: Error
                      example: |
                         {
                              "message": "Patinoire does not exist!"
                         }
            401:
                body:
                  application/json:
                      type: Error
                      example: |
                          {
                              "message": "Please authenticate."
                          }
                                      
        get:
          description: Get patinoire detail by is
          responses: 
              200:
                  body:
                      application/json:
                          type: object
                          example: 
                              {
                                  "nom_pat": "Aire de glissade ,Don-Bosco ()"
                              }
              404:
                  body:
                      application/json:
                          type: Error
                          example:
                            {
                                "message": "Patinoire does not exist!"
                            }
  /patinoire-condition:
      /{id}:
          uriParameters:
            id:
              type: number
              description: Patinoire condition identifier
          put:
            description: edit a paticular condition of a specific patinoire
            headers: 
            body: 
              application/json:
                type: Object
                example: 
                    {
                         "arrose": false,
                         "date_heure": "2015-12-13T16:51:19",
                         "deblaye": true,
                         "ouvert": true,
                         "resurface": true
                    }
            responses:
                200:
                    body:
                        application/json:
                            type: Object
                            example: 
                                {
                                    "arrose": false,
                                    "date_heure": "2015-12-13T16:51:19",
                                    "deblaye": true,
                                    "ouvert": true,
                                    "resurface": true
                                }
                400:
                    body:
                      application/json:
                        type: Error
                        examples: !include examples/editpatconditionerrors.raml
                404:
                    body:
                      application/json:
                        type: Error
                        example:
                          {
                              "message": "Condition does not exist!"
                          }
          delete:
              description: Remove a condition by its id from a patinoire
              headers:
                  Authorization:
                      type: string
                      description: Basic authentication header
                      example: |
                          Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
              responses:
                200:
                    body:
                      application/json:
                          type: object
                          example: |
                              {
                                  "arrose": true,
                                  "date_heure": "2018-01-07T03:29:27",
                                  "deblaye": true,
                                  "ouvert": true,
                                  "resurface": true
                              }
                404:
                    body:
                      application/json:
                          type: Error
                          example: 
                            {
                                "message": "Condition does not exist!"
                            }
                401:
                    body:
                      application/json:
                          type: Error
                          example: |
                              {
                                  "message": "Please authenticate."
                              }
          get:
              description: Get a paticular condition of a specific patinoire
              responses: 
                  200:
                      body:
                          application/json:
                              type: object
                              example: 
                                  {
                                      "arrose": false,
                                      "date_heure": "2002-01-08T12:50:34",
                                      "deblaye": false,
                                      "ouvert": false,
                                      "resurface": false
                                  }
                  404:
                      body:
                          application/json:
                              type: Error
                              example:
                                {
                                    "message": "Condition does not exist!"
                                }

  /authenticate:
    # get:
    #   headers:
    #     Authorization:
    #       type: string
    #       description: Basic authentication header
    #       example: |
    #         Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    post:
      description: authenticate
      headers: 
        Authorization:
          type: string
          description: Basic authentication header
          example: |
            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
      responses:
        200:
          headers:
            Set-Cookie:
              type: string
              example:
                id=78; Expires=Tue, 07 Dec 2021 04:49:04 GMT; Max-Age=28800; Path=/
        401:
          body:
            application/json:
              type: Error
              example: 
                {"message": "Please authenticate." }
  
